apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfserving-models-web-app
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfserving-models-web-app-cluster-role
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
- apiGroups:
  - serving.kubeflow.org
  resources:
  - inferenceservices
  - inferenceservices/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  - services/status
  - routes
  - routes/status
  - configurations
  - configurations/status
  - revisions
  - revisions/status
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kfserving-models-web-app-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kfserving-models-web-app-cluster-role
subjects:
- kind: ServiceAccount
  name: kfserving-models-web-app
  namespace: kubeflow
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kfserving-models-web-app
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /models/
    rewrite:
      uri: /
    route:
    - destination:
        host: kfserving-models-web-app.kubeflow.svc.cluster.local
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kfserving-models-web-app
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/component: kfserving-models-web-app
  type: ClusterIP
---
apiVersion: v1
data:
  APP_DISABLE_AUTH: "True"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kfserving-models-web-app
    kustomize.component: kfserving-models-web-app
  name: kfserving-models-web-app-config
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfserving-models-web-app
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kfserving-models-web-app
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/component: kfserving-models-web-app
    spec:
      containers:
      - image: kfserving/models-web-app:v0.6.0
        imagePullPolicy: IfNotPresent
        name: kfserving-models-web-app
        envFrom:
          - configMapRef:
              name: kfserving-models-web-app-config
        ports:
        - containerPort: 5000
      serviceAccountName: kfserving-models-web-app
