kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline-runner
  namespace: kubeflow-user-example-com

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - persistentvolumes
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflows
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - '*'
    apiGroups:
      - kubeflow.org
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner
  namespace: kubeflow-user-example-com
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow-user-example-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-runner